version: "3"

services:
  db:
    image: mysql:8.0
    restart: always   # Giữ MySQL luôn chạy
    ports:
      - "3315:3306"
    volumes:
      - /db_signage/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "cms"

  xmr:
    image: ghcr.io/xibosignage/xibo-xmr:develop
    restart: always   # Giữ XMR luôn chạy
    ports:
      - "9505:9505"
    environment:
      XMR_DEBUG: "true"
      IPV6PUBSUPPORT: "false"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always   # Giữ Web Server luôn chạy
    volumes:
      - ./:/var/www/cms
    ports:
      - "81:80"
    environment:
      CMS_DEV_MODE: "true"
      MYSQL_DATABASE: "cms"

  memcached:
    image: memcached:alpine
    restart: always   # Giữ Memcached luôn chạy
    command: memcached -m 15

  swagger:
    image: swaggerapi/swagger-ui:latest
    restart: always   # Giữ Swagger luôn chạy
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://localhost/swagger.json

  quickchart:
    image: ianw/quickchart
    restart: always   # Giữ QuickChart luôn chạy
