version: "3.8"

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24  # Định nghĩa dải mạng

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3315:3306"
    volumes:
      - ./db/:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - ./init_triggers.sh:/docker-entrypoint-initdb.d/init_triggers.sh
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "cms"
      MYSQL_USER: "cms"
      MYSQL_PASSWORD: "root"
      TZ: "Asia/Ho_Chi_Minh"
    networks:
      custom_network:
        ipv4_address: 192.168.1.100   # Gán IP tĩnh cho MySQL

  xmr:
    image: ghcr.io/xibosignage/xibo-xmr:develop
    restart: always
    ports:
      - "9505:9505"
    environment:
      XMR_DEBUG: "true"
      IPV6PUBSUPPORT: "false"
    networks:
      custom_network:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/var/www/cms
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "81:80"
    environment:
      CMS_DEV_MODE: "false"
      MYSQL_DATABASE: "cms"
      TZ: "Asia/Ho_Chi_Minh"
      MYSQL_PASSWORD: "root"
      MYSQL_USER: "cms"
      MYSQL_HOST: "192.168.1.100"  # Trỏ trực tiếp tới IP tĩnh của db
    networks:
      custom_network:

  memcached:
    image: memcached:alpine
    restart: always
    command: memcached -m 15
    networks:
      custom_network:

  swagger:
    image: swaggerapi/swagger-ui:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://localhost/swagger.json
    networks:
      custom_network:

  quickchart:
    image: ianw/quickchart
    restart: always
    networks:
      custom_network:
