<?php

/*
 * Xibo - Digital Signage - http://www.xibo.org.uk
 *
 * This file is part of Xibo - and is automatically generated by the installer
 *
 * You should not need to edit this file, unless your SQL connection details have changed.
 */

defined('XIBO') or die(__("Sorry, you are not allowed to directly access this page.") . "<br />" . __("Please press the back button in your browser."));

global $dbhost;
global $dbuser;
global $dbpass;
global $dbname;
global $dbssl;
global $dbsslverify;

$dbhost = isset($_SERVER['MYSQL_HOST']) ? $_SERVER['MYSQL_HOST'] : 'db';
$dbport = isset($_SERVER['MYSQL_PORT']) ? $_SERVER['MYSQL_PORT'] : '3306';
$dbuser = isset($_SERVER['MYSQL_USER']) ? $_SERVER['MYSQL_USER'] : 'root';
$dbpass = isset($_SERVER['MYSQL_PASSWORD']) ? $_SERVER['MYSQL_PASSWORD'] : 'root';
$dbname = isset($_SERVER['MYSQL_DATABASE']) ? $_SERVER['MYSQL_DATABASE'] : 'cms';

$dbhost = $dbhost . ':' . $dbport;

$dbsslverify = $_SERVER['MYSQL_ATTR_SSL_VERIFY_SERVER_CERT'];

if (!defined('SECRET_KEY')) {
    define('SECRET_KEY', 'au0amdI2');
}

if (array_key_exists('CMS_USE_MEMCACHED', $_SERVER)
    && ($_SERVER['CMS_USE_MEMCACHED'] === true || $_SERVER['CMS_USE_MEMCACHED'] === 'true')
) {
    global $cacheDrivers;
    $cacheDrivers = [
        new Stash\Driver\Memcache([
            'servers' => [$_SERVER['MEMCACHED_HOST'], $_SERVER['MEMCACHED_PORT']],
            'CONNECT_TIMEOUT' => 10,
        ])
    ];
}

/* ==========================
 * Thiết lập theme mặc định và menu điều hướng
 * ========================== */
$mysqli = new mysqli($dbhost, $dbuser, $dbpass, $dbname);

if ($mysqli->connect_error) {
    die("Database connection failed: " . $mysqli->connect_error);
}

$mysqli->query("UPDATE setting SET value = 'default' WHERE setting = 'GLOBAL_THEME_NAME'");
$mysqli->query("UPDATE setting SET value = 'horizontal' WHERE setting = 'NAVIGATION_MENU_POSITION'");
$mysqli->query("UPDATE setting SET value = 'vi_VN' WHERE setting = 'DEFAULT_LANGUAGE'");

$mysqli->close();

?>
